// ── icebreaker question bank ───────────────────────────────
// What:  fun, low-pressure icebreaker questions the new-member greeter appends
//        after a pack-voiced welcome framing (see each pack’s greeter.framings
//        and features/greeter/welcomeNewMember). Voice-neutral on purpose so the
//        one bank serves every plugin pack: the framing carries the kingdom vs
//        neutral voice, these carry the variety.
// Who:   welcomeNewMember picks one at random per join.
// How:   generated + deduped 2026-06-19. Edit freely (add/remove/reword lines).
//        Each entry is a single self-contained question, SFW, with no survey,
//        analytics, or personal-data prompts.

export const ICEBREAKERS: string[] = [
	"Pineapple on pizza: glorious or a crime against humanity?",
	"What's a snack you could eat every single day and never get tired of?",
	"Be honest, how many chicken nuggets could you realistically eat in one sitting?",
	"Cereal before milk or milk before cereal?",
	"What weird food combo do you secretly love that horrifies everyone else?",
	"If you had to delete one vegetable from existence forever, which one's gone?",
	"Crunchy peanut butter or smooth, and are you ready to defend it?",
	"What's the most chaotic thing you've ever put on toast?",
	"Hot fries dipped in ice cream: yes or absolutely not?",
	"What food do people say is overrated but you'd happily marry?",
	"Ketchup or mustard, and is there a wrong answer?",
	"What's your go-to order when you let the menu decide for you?",
	"Would you rather give up cheese or chocolate for a year?",
	"What snack instantly makes any movie better?",
	"Dunk the cookie in milk or eat it dry like a rebel?",
	"What's a food you were scared of as a kid but love now?",
	"If fruit could talk, which one would be the most annoying?",
	"Sweet breakfast or savory breakfast, pick your fighter?",
	"What's the strangest pizza topping you'd actually try?",
	"Tacos or burritos, and may the best wrap win?",
	"What drink could you sip forever and never get bored of?",
	"Be real, do you eat the pizza crust or leave the little bones?",
	"What's a food combo that sounds gross but is secretly a banger?",
	"Spicy enough to cry or mild and cozy?",
	"If you could only season everything with one spice forever, what is it?",
	"What's the snack you always sneak into the cart at the store?",
	"Waffles or pancakes, and is syrup mandatory?",
	"What food would you pick for your last meal ever?",
	"Do you bite the chocolate bunny ears first or commit a crime?",
	"What's the most random thing in your fridge right now?",
	"Fries or onion rings, choose wisely?",
	"What food do you eat in a totally weird order that confuses people?",
	"Cold pizza for breakfast: champion move or a sign of giving up?",
	"If snacks had a championship, which one takes the trophy?",
	"What's a flavor that should not exist but somehow does?",
	"Soup: a meal or just a hot drink in disguise?",
	"What's your unhinged hot take about a popular food?",
	"Would you rather have unlimited tacos or unlimited pizza forever?",
	"What's the one food you refuse to share with anybody?",
	"Do you eat the icing first or save the best for last?",
	"What snack would you grab if the apocalypse started in five minutes?",
	"Hard taco shell or soft, and how messy are we talking?",
	"What's a food you could cook with your eyes closed?",
	"If you had a personal milkshake flavor named after you, what's in it?",
	"Salty snacks or sweet snacks, and which one wins at 2am?",
	"If you woke up tomorrow able to teleport anywhere, where's the first place you'd pop into?",
	"Flight or invisibility, and what sneaky thing would you do with the winner?",
	"What superpower would you secretly abuse just to get out of chores?",
	"If you could pause time for everyone but yourself, what's the first thing you'd do?",
	"Would you rather read minds or control the weather?",
	"Imagine you can talk to animals starting now, which one are you chatting up first?",
	"What's a totally useless superpower you'd still love to have?",
	"If your phone-charging level was a superpower, how powerful would you be?",
	"Super strength or super speed, and which one helps you win at snacks?",
	"What power would you give your worst enemy as a prank?",
	"If you could shapeshift into any animal for a day, what are you turning into?",
	"Pick a power that only works on Mondays, what is it?",
	"Would you rather breathe underwater or never need sleep again?",
	"What everyday task would you upgrade with a tiny superpower?",
	"If you had the power to instantly clean any room, would you ever leave home?",
	"Mind control or time travel, and what's the catch you'd accept?",
	"What's the laziest way you'd use the ability to teleport?",
	"If you could summon any food out of thin air, what appears first?",
	"Would you rather be super lucky or super smart?",
	"What superpower would make you absolutely unbeatable at hide and seek?",
	"If you could give one celebrity a random superpower, who gets what?",
	"Healing powers or super speed, which one are you grabbing?",
	"What's the pettiest way you'd use invisibility?",
	"If you could control one element (fire, water, earth, air), which calls to you?",
	"Would you rather always know the truth or always get away with a lie?",
	"What power would you trade your sense of taste for, if any?",
	"If you could duplicate yourself, what would your clone be doing right now?",
	"Telekinesis or teleportation for getting the TV remote, which wins?",
	"What's a superpower you'd refuse even if it was free?",
	"If you could turn invisible but only while singing, would you still use it?",
	"Would you rather glow in the dark or never get tired?",
	"What superhero name would you pick for your most ridiculous power?",
	"If you could freeze one moment forever, would you abuse it for naps?",
	"Super hearing or super sight, and what would you immediately regret?",
	"What chore would instantly become fun with a magic power?",
	"If your pet could grant you one power, what do you think they'd choose?",
	"Would you rather control gravity or control time, just a little?",
	"What's the most chaotic good use of mind reading you can imagine?",
	"If you could only fly two feet off the ground, would you still brag about it?",
	"What power would you want during a really boring meeting?",
	"Invisibility or teleportation for skipping lines, which saves more time?",
	"If you could make any object talk, what are you interviewing first?",
	"Would you rather never feel cold or never feel hot again?",
	"What superpower would you absolutely waste on tiny everyday wins?",
	"If you got one power but it came with a silly side effect, what's the trade?",
	"Would you rather have fingers as long as your legs or legs as long as your fingers?",
	"Would you rather be able to teleport anywhere or read minds for a day?",
	"Would you rather fight one horse-sized duck or a hundred duck-sized horses?",
	"Would you rather always be slightly too hot or slightly too cold?",
	"Would you rather have a permanent unicorn horn or a permanent dragon tail?",
	"Would you rather only whisper for the rest of your life or only shout?",
	"Would you rather have free pizza forever or free tacos forever?",
	"Would you rather be able to talk to animals or speak every human language?",
	"Would you rather live in a treehouse or a cozy underground burrow?",
	"Would you rather sneeze glitter or burp tiny bubbles?",
	"Would you rather have a pause button for life or a rewind button?",
	"Would you rather be the funniest person in any room or the smartest?",
	"Would you rather have a pet dragon the size of a cat or a cat the size of a dragon?",
	"Would you rather always know the time exactly or always know which direction is north?",
	"Would you rather wear a cape everywhere or a crown everywhere?",
	"Would you rather have spaghetti for hair or marshmallows for teeth?",
	"Would you rather be able to fly slowly or run super fast?",
	"Would you rather never have to sleep or never have to eat?",
	"Would you rather have a robot best friend or a talking houseplant?",
	"Would you rather slide down a giant rainbow or bounce on a giant cloud?",
	"Would you rather have an endless supply of stickers or an endless supply of socks?",
	"Would you rather control the weather or control all the traffic lights?",
	"Would you rather hiccup confetti or yawn rainbows?",
	"Would you rather have a tiny pocket-sized elephant or a giant hamster you can ride?",
	"Would you rather always smell freshly baked cookies or freshly cut grass?",
	"Would you rather be able to breathe underwater or walk through walls?",
	"Would you rather have a personal theme song that plays when you enter or your own laugh track?",
	"Would you rather turn invisible at will or change your hair color with a thought?",
	"Would you rather have shoes that never wear out or a phone that never dies?",
	"Would you rather befriend a friendly ghost or a tiny mischievous goblin?",
	"Would you rather have a slide instead of stairs or a trampoline instead of a couch?",
	"Would you rather taste colors or hear flavors?",
	"Would you rather have a magic backpack that holds anything or a hat that pulls out snacks?",
	"Would you rather ride a dolphin to school or a giant eagle to work?",
	"Would you rather have hands for feet or feet for hands?",
	"Would you rather always win at board games or always win at karaoke?",
	"Would you rather have a tail you can wag or ears you can wiggle on command?",
	"Would you rather live one day as a giant or one day shrunk to ant size?",
	"Would you rather have a butler made of cardboard or a chef who only makes breakfast food?",
	"Would you rather be able to summon any snack instantly or any song instantly?",
	"Would you rather have a permanent superhero costume or a permanent wizard robe?",
	"Would you rather swap voices with a cartoon character or laugh like one forever?",
	"Would you rather have a moat around your home or a drawbridge to your bedroom?",
	"Would you rather grow flowers from your sleeves or tiny stars from your hair?",
	"Would you rather have a remote that mutes annoying sounds or fast-forwards boring moments?",
	"What movie can you quote start to finish without even trying?",
	"Which TV show finale left you completely shook?",
	"What book do you secretly think everyone should read?",
	"Which song instantly makes you turn the volume all the way up?",
	"What is the one movie you rewatch every single time it is on?",
	"Which fictional character would you most want as a roommate?",
	"What is a song you are a little embarrassed to love but love anyway?",
	"Which movie made you cry harder than you would like to admit?",
	"What show did you binge way too fast and immediately regret finishing?",
	"If your life had a theme song, what would be playing right now?",
	"What is the most rewatched comfort movie in your rotation?",
	"Which book character do you wish was real so you could be friends?",
	"What is a movie everyone loves that you just do not get?",
	"Which TV theme song do you refuse to skip?",
	"What song could you listen to on repeat for a whole day?",
	"Which movie villain is secretly your favorite character?",
	"What book made you stay up way past your bedtime?",
	"Which fictional world would you move into in a heartbeat?",
	"What is the funniest movie you have ever watched?",
	"Which song takes you straight back to being a kid?",
	"What show do you put on just to fall asleep to?",
	"Which movie sequel was actually better than the first one?",
	"What is a book that totally lived in your head for weeks?",
	"Which song do you absolutely belt out in the shower?",
	"What movie scared you so badly you still think about it?",
	"Which TV character would you trust with your last slice of pizza?",
	"What is your go to feel good movie after a rough day?",
	"Which song never fails to get you dancing?",
	"What book would you save if you could only keep one?",
	"Which movie has the best plot twist you never saw coming?",
	"What show got you completely obsessed out of nowhere?",
	"Which fictional pet would you adopt immediately?",
	"What is the catchiest song that has been stuck in your head lately?",
	"Which movie soundtrack is better than the movie itself?",
	"What book did you finish in one sitting because you could not stop?",
	"Which cartoon could you happily rewatch as an adult?",
	"What is a movie line you randomly drop into conversation?",
	"Which song would you pick for the credits of your life story?",
	"What show do you wish you could watch again for the very first time?",
	"Which movie snack combo is non negotiable for you?",
	"What is a song that instantly puts you in a good mood?",
	"Which book ending made you yell at the pages?",
	"What movie do you defend even when people make fun of you for it?",
	"Which TV duo has the best friendship of all time?",
	"What is the one album you could survive on forever?",
	"What was the very first video game that completely hooked you?",
	"Are you a button masher or a strategic patient player?",
	"Which video game character would you actually trust with your house keys?",
	"What is your most embarrassing gaming guilty pleasure?",
	"Do you read the in-game lore or skip straight to the action?",
	"Which fictional video game world would you most want to live in?",
	"What is the hardest boss fight you have ever rage quit?",
	"Are you the type who finishes every side quest before the main story?",
	"Which video game soundtrack still lives rent free in your head?",
	"What game made you say just one more turn and then it was 3am?",
	"Would you rather have unlimited lives or unlimited save points in real life?",
	"Which classic arcade game could you crush right now?",
	"What is the most chaotic thing you have done in an open world game?",
	"Do you name your save files or leave them as default slot one?",
	"Which video game pet or companion stole your whole heart?",
	"What genre do you secretly love but pretend you are too cool for?",
	"Have you ever cried over a video game cutscene?",
	"Which retro console do you have the most nostalgia for?",
	"Are you a loot hoarder or do you sell everything immediately?",
	"What video game snack and drink combo is your perfect setup?",
	"Which game villain is so good you almost wanted them to win?",
	"Do you play on easy mode for the story or hard mode for the bragging rights?",
	"What is the silliest reason you ever quit playing a game?",
	"Which video game would make a surprisingly great theme park?",
	"Have you ever spent more time in character creation than playing?",
	"What is your go to comfort game when you just want to relax?",
	"Which co-op game has ended or strengthened a friendship for you?",
	"Do you talk to the NPCs or run right past them?",
	"What gaming skill do you have that is completely useless in real life?",
	"Which video game vehicle would you most want to drive for a day?",
	"Are you a collect every achievement person or a play for fun person?",
	"What game did everyone love that you just could not get into?",
	"Which power up would you steal from a game and use in real life?",
	"Do you keep your inventory tidy or is it pure chaos?",
	"What is the most times you have replayed the same game?",
	"Which game made you yell at your screen the loudest?",
	"Are you team controller or team keyboard and mouse?",
	"What fictional weapon from a game would you hang on your wall?",
	"Which video game world has the snacks you most want to taste?",
	"Have you ever gotten lost in a game and just enjoyed the scenery?",
	"What is your hottest take about a wildly popular game?",
	"Which game tutorial do you skip even though you probably should not?",
	"Do you sprint to the finish or wander every corner of the map?",
	"What gaming moment made you jump out of your seat?",
	"Which video game character has the best outfit you would actually wear?",
	"If a free plane ticket appeared right now, where would you tell the pilot to go?",
	"Beach, mountains, or big city for your perfect getaway?",
	"What's one place you would teleport to for breakfast and be home by lunch?",
	"Window seat or aisle seat, and why is your answer correct?",
	"What country is sitting at the top of your someday list?",
	"Would you rather wander a foreign city with no map or a perfectly planned itinerary?",
	"If you could swap your view out the window with anywhere on Earth, what would you pick?",
	"What's the dreamiest place you have ever seen in a photo and instantly wanted to visit?",
	"Road trip with friends or a solo train ride through the countryside?",
	"Name a place you would happily eat your way across for a whole week?",
	"If you could pack a bag in five minutes and vanish anywhere, where to?",
	"What's a city you have never been to but already feel weirdly fond of?",
	"Tropical island paradise or a cozy cabin tucked in the snow?",
	"If a genie granted you one round trip anywhere, what's the destination?",
	"What's the longest trip you would take if time and packing magically did not exist?",
	"Would you rather explore ancient ruins or a buzzing night market?",
	"What's the one landmark you would cross the planet just to stand in front of?",
	"Camping under the stars or a fancy hotel with a ridiculous view?",
	"If you could live in any city for one year, which one gets the lucky slot?",
	"What's a place whose food alone would justify the entire trip?",
	"Pick a season and a destination that go together perfectly in your head?",
	"Would you rather chase the northern lights or a sunset on a warm coast?",
	"If your next vacation had a theme song, where would it be playing?",
	"What's somewhere you would visit just for the snacks?",
	"Sleepy seaside village or a city that never goes quiet?",
	"If you could teleport once a day, where would your daily detour be?",
	"What's a destination you would drag your whole friend group to in a heartbeat?",
	"Hot air balloon, sailboat, or scenic train for your dream way to travel?",
	"What's one place you would happily get pleasantly lost in for an afternoon?",
	"If you woke up somewhere new tomorrow, where do you secretly hope it would be?",
	"Pick a country to be your home for a month based purely on vibes?",
	"What's the most magical-sounding place name you would visit just because?",
	"Would you rather hike a jaw-dropping trail or stroll a charming old town?",
	"If postcards were real portals, which one would you step through first?",
	"What's a place you would visit just to nap in the most scenic spot possible?",
	"Desert dunes, rainforest canopy, or icy glacier for your bucket-list backdrop?",
	"If money grew on trees, what's the first trip you would book?",
	"What's the coziest little spot you would love to spend a rainy day in?",
	"Would you rather see seven wonders quickly or know one city inside out?",
	"Name a place you would visit just to people-watch at a perfect cafe?",
	"If you could borrow someone's vacation photos and step into one, which scene?",
	"What's the wildest, farthest corner of the map you would actually go to?",
	"Sunrise hike or midnight stroll through a glowing city, and where?",
	"If your dream trip came with one superpower, where would you put it to use?",
	"What's a place you would happily revisit a hundred times and never get bored?",
	"What was the one cartoon you'd wake up early on a Saturday to watch?",
	"What snack instantly teleports you back to being a kid?",
	"Which toy did you absolutely refuse to share with anyone?",
	"What's a candy from your childhood that you'd hoard like treasure?",
	"Which cartoon theme song could you still sing word for word right now?",
	"What playground game did you take way too seriously as a kid?",
	"What's the snack you'd beg your parents to buy at the store?",
	"Which video game character did you have a tiny crush on growing up?",
	"What's a toy you wish they still made today?",
	"Which cereal did you only want for the prize inside the box?",
	"What show did you pretend to be sick to stay home and watch?",
	"Which childhood cartoon villain low-key terrified you?",
	"What was your go-to recess activity back in the day?",
	"Which animated movie made you cry the hardest as a kid?",
	"What's a drink you guzzled as a kid that you'd never touch now?",
	"Which board game caused the most family arguments at your house?",
	"What toy got the most action figures or accessories in your collection?",
	"Which cartoon sidekick deserved their own spin-off show?",
	"What's a snack combo you invented as a kid that sounded gross but slapped?",
	"Which song from a kids' movie still lives rent free in your head?",
	"What was your favorite flavor of those colorful ice pops?",
	"Which childhood game show would you have absolutely dominated?",
	"What toy commercial jingle is permanently stuck in your brain?",
	"Which cartoon would you binge all over again if you had the day off?",
	"What was the coolest thing you ever found in a cereal box?",
	"Which video game did you rage quit the most as a kid?",
	"What's a snack your school cafeteria served that you secretly miss?",
	"Which Saturday morning cartoon had the best opening sequence?",
	"What toy did everyone in your class suddenly have to own?",
	"Which childhood candy do you defend even though it's objectively weird?",
	"What cartoon animal did you wish was your actual pet?",
	"Which video game level haunted your dreams growing up?",
	"What's the first movie you remember watching over and over again?",
	"Which playground rumor did you 100 percent believe as a kid?",
	"What snack do you still eat the exact same weird way you did as a kid?",
	"Which cartoon catchphrase do you still randomly say out loud?",
	"What was your prized possession in your toy box?",
	"Which kids' show character would you trust to babysit?",
	"What's a treat you only got on special occasions growing up?",
	"Which animated duo had the best friendship of your childhood?",
	"What game did you make up your own rules for as a kid?",
	"Which toy was way more fun to play with than its box suggested?",
	"What's a cartoon snack you always wished was real and edible?",
	"Which video game soundtrack would you still listen to today?",
	"What's the one childhood thing you'd bring back in a heartbeat?",
	"A squirrel just challenged you to a duel, but it gets to pick the weapon: what does it grab?",
	"Your shadow has decided to quit and walk off on its own: what's the first thing it does without you?",
	"A pigeon learns to talk and follows you everywhere narrating your life: what's its catchphrase?",
	"You wake up as a houseplant for one day: which window do you want to sit in?",
	"Every spoon in your kitchen can now sing: what genre are they into?",
	"A wise old goldfish offers you exactly one piece of advice: what does it bubble out?",
	"You can swap bodies with any animal until sunset: who are you and what's your first move?",
	"Your phone becomes a tiny dragon overnight: is it helpful or pure chaos?",
	"If your socks held a secret meeting while you slept, what would they complain about?",
	"A cloud follows you around like a loyal pet: do you name it, and what?",
	"You're suddenly fluent in cat: what's the first thing a cat tells you?",
	"Your fridge gains a personality: is it sassy, sleepy, or dramatic?",
	"A talking raccoon wants to be your life coach: do you let it, and why?",
	"You shrink small enough to ride a bumblebee: where do you fly first?",
	"Your reflection waves back but it's clearly up to something: what's it planning?",
	"A penguin shows up at your door insisting it's your long-lost cousin: how does dinner go?",
	"You can turn into any kitchen appliance for an hour: which one and what mischief?",
	"Gravity takes a coffee break for ten minutes: what's the first thing you do mid-float?",
	"Your pillow could talk and it's seen everything: what's its honest review of your sleeping?",
	"A snail challenges you to a race but it's somehow winning: what's its secret?",
	"You become best friends with a sentient cardboard box: what adventures await?",
	"Every door you open now leads somewhere random: where do you hope the next one goes?",
	"A wizard turns you into a vegetable, but you get to choose which: what are you?",
	"Your left shoe and right shoe are arguing: what are they fighting about?",
	"You can have a meaningful conversation with one inanimate object: what do you pick?",
	"A jellyfish floats up and asks to crash on your couch: yes or no, and why?",
	"You woke up the size of a thumb: what's the scariest household item now?",
	"Your toaster falls in love with the blender: do you support this romance?",
	"A flock of geese elects you as their leader: what's your first decree?",
	"You can breathe underwater but only while singing: what song keeps you alive?",
	"Your hair grows a mind of its own and wants to go places: where does it drag you?",
	"A friendly ghost wants to learn one human hobby from you: what do you teach it?",
	"You trade lives with your favorite chair for a week: how do you spend it?",
	"An octopus offers to give you a high four (all eight arms busy): do you accept?",
	"Your alarm clock comes alive and refuses to wake you up ever again: how's your morning?",
	"You can make any one object grow legs and follow you: what gets a pair?",
	"A very polite bear knocks asking to borrow a cup of honey: what do you say?",
	"You're a sock in the dryer for one cycle: thrilling or terrifying?",
	"Your sneeze could teleport you anywhere: where do you end up after the next one?",
	"A worm in a tiny hat asks you for directions: where is it trying to go?",
	"You can swap voices with any animal for a day: whose do you steal?",
	"Your morning cereal starts giving you life advice: do you trust it?",
	"A moth admits it's been following you for the vibes, not the light: how do you respond?",
	"You become the wind for one afternoon: whose hat are you stealing first?",
	"A duck hands you a tiny briefcase and says you'll know what to do: what's inside?",
	"What is the most useless talent you secretly take great pride in?",
	"Can you wiggle your ears, raise one eyebrow, or do some other weird face trick?",
	"What random skill could you teach a complete beginner in under five minutes?",
	"Got any party trick that wows people for about three seconds before they move on?",
	"What is something you are surprisingly good at that almost never comes up?",
	"Can you whistle, snap, or hum better than the average human?",
	"What hidden talent would you reveal if someone handed you a microphone right now?",
	"Are you the person who can open a snack bag perfectly or the one who explodes it everywhere?",
	"What is a skill you picked up purely out of boredom?",
	"Can you touch your nose with your tongue, and be honest about it?",
	"What is the oddest thing you can do with your hands or fingers?",
	"Do you have a hidden knack for guessing what time it is without a clock?",
	"What is one thing you can fold, flip, or balance that mildly impresses people?",
	"Are you secretly amazing at any specific video game, board game, or card trick?",
	"What talent do you wish you had but absolutely do not?",
	"Can you do any accent or impression that makes people laugh?",
	"What is the weirdest food combination you can somehow eat with no shame?",
	"Do you have a party trick involving juggling, spinning, or balancing something?",
	"What is a tiny skill that makes you feel like a genius every single time?",
	"Can you recite anything from memory that serves zero practical purpose?",
	"What is your signature move on a dance floor, even if it is terrible?",
	"Are you the friend who can fix anything or the one who makes it worse?",
	"What can you draw really well versus what looks like a sad potato?",
	"Do you have any sound effect or noise you can make perfectly?",
	"What is a skill you are oddly confident about until someone actually watches?",
	"Can you solve a Rubik's cube, and how long are we talking?",
	"What is the most impressive thing you can do while half asleep?",
	"Do you have a hidden talent for remembering totally random facts?",
	"What everyday object could you spin on a finger or balance on your nose?",
	"Are you secretly great at parking, parallel or otherwise?",
	"What is one trick you can do that you learned just to show off?",
	"Can you tie a cherry stem in a knot, or is that just a myth to you?",
	"What skill makes you the unexpected hero in a group of friends?",
	"Do you have any talent that only works after exactly one attempt?",
	"What is the strangest thing your body can do that surprises people?",
	"Can you do a cartwheel, a handstand, or something that defies gravity?",
	"What hidden skill would you put on a resume if honesty did not matter?",
	"Are you weirdly good at finding lost things for other people?",
	"What is a tiny magic trick or illusion you can pull off?",
	"Do you have a talent for naming a song within the first two seconds?",
	"What is something you can build, assemble, or stack faster than most people?",
	"Can you make any animal sound convincingly enough to fool someone?",
	"What is your most niche superpower that the world has yet to appreciate?",
	"Are you the one who can flip a pancake midair or the one praying it lands?",
	"What completely random thing are you a self-declared expert at?",
	"Cats vs dogs, which energy are you running on today?",
	"If your phone camera roll is mostly one animal, which one is it?",
	"What animal would you trust the least to keep a secret?",
	"Be honest, would your dream pet be tiny, huge, or terrifyingly fluffy?",
	"Which animal do you think is secretly judging all of us?",
	"If you woke up as a house cat tomorrow, first move?",
	"What pet would you adopt if size, money, and physics were no issue?",
	"Dog person, cat person, or chaotic third option?",
	"Which animal would make the worst roommate and why?",
	"If you had a spirit animal, what would it be on a low-energy day?",
	"What's the most underrated animal that deserves more hype?",
	"Would you rather have a pet that talks or a pet that can fly?",
	"Which animal do you think would absolutely dominate at a video game?",
	"If you could give one animal a tiny job, who gets hired and for what?",
	"What creature would you want guarding your snacks?",
	"Penguin, otter, or capybara, pick your vibe?",
	"If your pet could text you, what would their first message say?",
	"What animal would you be in a past life, no logic required?",
	"Which animal has the best walk, strut, or general swagger?",
	"Would you survive owning a tiny dinosaur as a pet?",
	"What's the goofiest animal sound you can actually do?",
	"If animals had a group chat, who's typing in all caps?",
	"Which animal do you think would give the best hugs?",
	"Would you rather befriend a wolf or a giant friendly bear?",
	"What pet name would you give a goldfish to make it sound dramatic?",
	"Which animal would you cast as the villain in a cartoon?",
	"If you could shrink any wild animal to pocket size, who comes with you?",
	"What's a small creature that scares you way more than it should?",
	"Which animal do you think naps the most luxuriously?",
	"If you had to enter a staring contest with one animal, who wins?",
	"What pet would make the best detective?",
	"Owl, fox, or raccoon, who matches your 2am brain?",
	"Which animal would you trust to plan your birthday party?",
	"If your energy was an animal right now, what's hovering nearby?",
	"What creature would you want narrating your daily life?",
	"Which animal deserves its own talk show?",
	"Would you rather have a pet that glows or a pet that purrs like a motor?",
	"What animal would absolutely refuse to follow any rules?",
	"If you could understand one animal's language, which do you pick?",
	"Which animal would crush it as a professional athlete?",
	"What's the cutest animal that could probably take you in a fight?",
	"If you adopted a dragon, what would you feed it for breakfast?",
	"Which animal would be the most dramatic if it could talk?",
	"Sloth pace or hummingbird pace, what's your speed today?",
	"What animal would you want as a tiny shoulder companion all day?",
	"Are you a morning person or do you come alive after dark?",
	"What is the very first thing you do after waking up?",
	"Tea or coffee to kick off the day?",
	"Do you make your bed every morning or leave it a beautiful mess?",
	"What is your go-to comfort breakfast?",
	"Are you a snooze-button warrior or an instant-out-of-bed type?",
	"Do you shower in the morning or at night?",
	"What is one tiny daily ritual you would never skip?",
	"Sweet breakfast or savory breakfast?",
	"Do you check your phone first thing or resist for a glorious few minutes?",
	"What is your ideal bedtime in a perfect world?",
	"Are you team early bird or team night owl?",
	"Do you have a favorite mug you always reach for?",
	"What sound do you wake up to, alarm or something gentler?",
	"Do you eat the same breakfast every day or mix it up?",
	"Toast crunchy or barely warmed?",
	"Do you plan your day the night before or just wing it?",
	"What is your weekend morning vibe, slow and cozy or up and out?",
	"Are you the type to lay out clothes the night before?",
	"Do you drink water first thing or dive straight into caffeine?",
	"What is your favorite midday pick-me-up snack?",
	"Do you have a wind-down routine before sleep?",
	"Socks on or socks off when you sleep?",
	"Are you a list maker or do you keep it all in your head?",
	"What is the one chore you secretly enjoy doing?",
	"Do you like a tidy desk or a creative chaos zone?",
	"Hot shower or refreshingly cold rinse?",
	"Do you talk before your morning coffee or stay in silent mode?",
	"What is your favorite way to spend the first hour of the day?",
	"Are you a meal prepper or a what-can-I-find-right-now eater?",
	"Do you read, scroll, or stare at the ceiling before falling asleep?",
	"What is your most-used emoji in everyday chats?",
	"Do you take the stairs or hunt for the elevator?",
	"Window seat or aisle seat when you travel?",
	"Do you fold laundry right away or let it live in the basket?",
	"What is your favorite cozy drink on a chilly evening?",
	"Are you an early arriver or a fashionably on-time person?",
	"Do you sing in the shower or save the vocals for later?",
	"What is the snack you always keep stocked at home?",
	"Do you make a to-do list or trust future-you to remember?",
	"Big breakfast or skip it and power through to lunch?",
	"Do you set one alarm or a hopeful little series of them?",
	"What is your favorite season to wake up to?",
	"Are you a slipper person or barefoot all the way?",
	"Do you keep your notifications on or live in blissful do-not-disturb?",
	"Stranded on a desert island with one snack forever, what's filling your pockets?",
	"One song to loop endlessly while you wait for rescue, what is it?",
	"Marooned alone, which fictional character do you want washed ashore next to you?",
	"You get one luxury item on the island, totally useless but joy-bringing, what's it?",
	"Pick one beverage to magically refill on your island, what's in the cup?",
];
